from database import SessionLocal, engine
import models
import os
import time
import urllib.request

models.Base.metadata.create_all(bind=engine)

DATA_DIR = os.environ.get("DATA_DIR", ".")
CATALOG_IMG_DIR = os.path.join(DATA_DIR, "uploads", "catalog")


def _download_image(plant_id: int, url: str) -> str | None:
    """Download image from url, save locally, return local path or None on failure."""
    os.makedirs(CATALOG_IMG_DIR, exist_ok=True)
    for attempt in range(3):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
            resp = urllib.request.urlopen(req, timeout=20)
            content_type = resp.headers.get("Content-Type", "image/jpeg")
            ext = ".png" if "png" in content_type else ".jpg"
            filename = f"plant_{plant_id}{ext}"
            with open(os.path.join(CATALOG_IMG_DIR, filename), "wb") as f:
                f.write(resp.read())
            time.sleep(2)
            return f"/uploads/catalog/{filename}"
        except Exception:
            if attempt < 2:
                time.sleep(5 * (attempt + 1))
    return None

WC = "https://commons.wikimedia.org/wiki/Special:FilePath"

CATALOG_PLANTS = [
    {
        "name": "Монстера делициоза",
        "latin_name": "Monstera deliciosa",
        "description": "Тропическое растение с крупными резными листьями. Отлично подходит для украшения интерьера.",
        "ideal_light": "Яркий рассеянный свет",
        "ideal_humidity": "60–80%",
        "ideal_temperature": "18–27°C",
        "watering_interval_days": 7,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 730,
        "care_notes": "Протирайте листья от пыли. Не переусердствуйте с поливом — корни могут загнить.",
        "difficulty": "Лёгкая",
        "category": "Тропические",
        "image_url": f"{WC}/Monstera_deliciosa.jpg?width=400",
    },
    {
        "name": "Фикус Бенджамина",
        "latin_name": "Ficus benjamina",
        "description": "Популярное деревце с мелкими глянцевыми листьями. Чувствителен к смене места.",
        "ideal_light": "Яркий рассеянный свет",
        "ideal_humidity": "50–70%",
        "ideal_temperature": "16–24°C",
        "watering_interval_days": 5,
        "fertilizing_interval_days": 21,
        "repotting_interval_days": 730,
        "care_notes": "Не переставляйте горшок. Опрыскивайте листья тёплой водой.",
        "difficulty": "Средняя",
        "category": "Деревья",
        "image_url": f"{WC}/Ficus_benjamina.jpg?width=400",
    },
    {
        "name": "Алоэ вера",
        "latin_name": "Aloe vera",
        "description": "Суккулент с мясистыми листьями, содержащими целебный гель.",
        "ideal_light": "Прямые и рассеянные солнечные лучи",
        "ideal_humidity": "30–50%",
        "ideal_temperature": "15–27°C",
        "watering_interval_days": 14,
        "fertilizing_interval_days": 60,
        "repotting_interval_days": 730,
        "care_notes": "Поливайте только когда почва полностью высохнет. Не допускайте застоя воды.",
        "difficulty": "Лёгкая",
        "category": "Суккуленты",
        "image_url": f"{WC}/Aloe_vera_flower_inset.png?width=400",
    },
    {
        "name": "Орхидея фаленопсис",
        "latin_name": "Phalaenopsis",
        "description": "Элегантная орхидея с длительным цветением. Одна из самых распространённых комнатных орхидей.",
        "ideal_light": "Рассеянный свет без прямых солнечных лучей",
        "ideal_humidity": "50–70%",
        "ideal_temperature": "18–25°C",
        "watering_interval_days": 7,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 730,
        "care_notes": "Поливайте погружением горшка в воду на 15 мин раз в неделю. Используйте специальный субстрат для орхидей.",
        "difficulty": "Средняя",
        "category": "Цветущие",
        "image_url": f"{WC}/Phalaenopsis_amabilis.jpg?width=400",
    },
    {
        "name": "Сансевиерия (тещин язык)",
        "latin_name": "Sansevieria trifasciata",
        "description": "Неприхотливое растение с вертикальными полосатыми листьями. Отлично очищает воздух.",
        "ideal_light": "Любое освещение",
        "ideal_humidity": "30–50%",
        "ideal_temperature": "16–27°C",
        "watering_interval_days": 14,
        "fertilizing_interval_days": 60,
        "repotting_interval_days": 1095,
        "care_notes": "Практически не требует ухода. Главная проблема — переполив.",
        "difficulty": "Лёгкая",
        "category": "Суккуленты",
        "image_url": f"{WC}/Sansevieria_trifasciata_pm.jpg?width=400",
    },
    {
        "name": "Спатифиллум",
        "latin_name": "Spathiphyllum",
        "description": "Изящное растение с белыми цветками-покрывалами. Хорошо растёт в тени.",
        "ideal_light": "Слабое или рассеянное освещение",
        "ideal_humidity": "60–80%",
        "ideal_temperature": "18–25°C",
        "watering_interval_days": 5,
        "fertilizing_interval_days": 21,
        "repotting_interval_days": 365,
        "care_notes": "Регулярно опрыскивайте. Поливайте при подсыхании верхнего слоя почвы.",
        "difficulty": "Лёгкая",
        "category": "Цветущие",
        "image_url": f"{WC}/Spathiphyllum_wallisii_a3.jpg?width=400",
    },
    {
        "name": "Хлорофитум хохлатый",
        "latin_name": "Chlorophytum comosum",
        "description": "Быстрорастущее ампельное растение с зелёными или пёстрыми листьями.",
        "ideal_light": "Яркий рассеянный или умеренный свет",
        "ideal_humidity": "40–60%",
        "ideal_temperature": "14–24°C",
        "watering_interval_days": 5,
        "fertilizing_interval_days": 21,
        "repotting_interval_days": 365,
        "care_notes": "Размножается усами с розетками. Очень неприхотлив.",
        "difficulty": "Лёгкая",
        "category": "Тропические",
        "image_url": f"{WC}/Hierbabuena_0611_Revised.jpg?width=400",
    },
    {
        "name": "Каланхоэ Блоссфельда",
        "latin_name": "Kalanchoe blossfeldiana",
        "description": "Суккулентное растение с яркими мелкими цветками различных оттенков.",
        "ideal_light": "Яркий свет, немного прямого солнца",
        "ideal_humidity": "40–60%",
        "ideal_temperature": "15–25°C",
        "watering_interval_days": 10,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 365,
        "care_notes": "После цветения обрежьте цветоносы. Для повторного цветения нужен период короткого дня.",
        "difficulty": "Средняя",
        "category": "Суккуленты",
        "image_url": f"{WC}/Kalanchoe_blossfeldiana.jpg?width=400",
    },
    {
        "name": "Замиокулькас",
        "latin_name": "Zamioculcas zamiifolia",
        "description": "Тропическое растение с блестящими тёмно-зелёными листьями. Очень устойчиво к засухе.",
        "ideal_light": "Рассеянный свет, переносит тень",
        "ideal_humidity": "40–60%",
        "ideal_temperature": "18–26°C",
        "watering_interval_days": 14,
        "fertilizing_interval_days": 30,
        "repotting_interval_days": 730,
        "care_notes": "Поливайте редко. Корни чувствительны к переливу.",
        "difficulty": "Лёгкая",
        "category": "Тропические",
        "image_url": f"{WC}/Zamioculcas_zamiifolia_1.jpg?width=400",
    },
    {
        "name": "Кактус эхинокактус",
        "latin_name": "Echinocactus grusonii",
        "description": "Шарообразный кактус с золотистыми колючками. Медленно растёт.",
        "ideal_light": "Прямое солнце",
        "ideal_humidity": "20–40%",
        "ideal_temperature": "15–30°C",
        "watering_interval_days": 21,
        "fertilizing_interval_days": 60,
        "repotting_interval_days": 730,
        "care_notes": "Зимой почти не поливайте. Нужен хороший дренаж.",
        "difficulty": "Лёгкая",
        "category": "Кактусы",
        "image_url": f"{WC}/.00_2563_Kaktus_(Echinocactus_grusonii).jpg?width=400",
    },
    {
        "name": "Драцена маргината",
        "latin_name": "Dracaena marginata",
        "description": "Стройное деревце с узкими зелёными листьями с красной каймой.",
        "ideal_light": "Рассеянный свет",
        "ideal_humidity": "40–60%",
        "ideal_temperature": "18–25°C",
        "watering_interval_days": 7,
        "fertilizing_interval_days": 30,
        "repotting_interval_days": 730,
        "care_notes": "Чувствительна к фтору в воде — используйте отстоянную воду.",
        "difficulty": "Средняя",
        "category": "Деревья",
        "image_url": f"{WC}/Starr_061231-3049_Dracaena_marginata.jpg?width=400",
    },
    {
        "name": "Антуриум",
        "latin_name": "Anthurium andraeanum",
        "description": "Тропическое растение с яркими восковыми цветками-покрывалами.",
        "ideal_light": "Яркий рассеянный свет",
        "ideal_humidity": "70–80%",
        "ideal_temperature": "18–25°C",
        "watering_interval_days": 5,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 365,
        "care_notes": "Высокая влажность обязательна. Опрыскивайте или ставьте поддон с галькой и водой.",
        "difficulty": "Сложная",
        "category": "Цветущие",
        "image_url": f"{WC}/Anthurium_andraeanum.jpg?width=400",
    },
    {
        "name": "Потос золотистый",
        "latin_name": "Epipremnum aureum",
        "description": "Быстрорастущая лиана с золотисто-зелёными листьями. Одно из самых неприхотливых растений.",
        "ideal_light": "Любое, кроме прямого солнца",
        "ideal_humidity": "40–60%",
        "ideal_temperature": "15–30°C",
        "watering_interval_days": 7,
        "fertilizing_interval_days": 30,
        "repotting_interval_days": 730,
        "care_notes": "Можно выращивать в воде. Хорошо очищает воздух. Ядовит для животных.",
        "difficulty": "Лёгкая",
        "category": "Тропические",
        "image_url": f"{WC}/Epipremnum_aureum1542991393.jpg?width=400",
    },
    {
        "name": "Традесканция",
        "latin_name": "Tradescantia zebrina",
        "description": "Ампельное растение с пёстрыми полосатыми листьями фиолетово-серебристых оттенков.",
        "ideal_light": "Яркий рассеянный свет",
        "ideal_humidity": "40–60%",
        "ideal_temperature": "15–25°C",
        "watering_interval_days": 5,
        "fertilizing_interval_days": 21,
        "repotting_interval_days": 365,
        "care_notes": "Для яркого окраса нужен хороший свет. Легко размножается черенками.",
        "difficulty": "Лёгкая",
        "category": "Тропические",
        "image_url": f"{WC}/Zebrina_pendula_20060521_2_closer.jpg?width=400",
    },
    {
        "name": "Диффенбахия",
        "latin_name": "Dieffenbachia seguine",
        "description": "Декоративное растение с крупными пёстрыми листьями. Хорошо растёт в полутени.",
        "ideal_light": "Рассеянный или слабый свет",
        "ideal_humidity": "60–70%",
        "ideal_temperature": "18–26°C",
        "watering_interval_days": 7,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 365,
        "care_notes": "Сок ядовит — работайте в перчатках. Протирайте листья от пыли.",
        "difficulty": "Средняя",
        "category": "Тропические",
        "image_url": f"{WC}/Dieffenbachia_seguine-02.jpg?width=400",
    },
    {
        "name": "Герань",
        "latin_name": "Pelargonium zonale",
        "description": "Обильно цветущее балконное и комнатное растение с ароматными листьями.",
        "ideal_light": "Прямое солнце или яркий свет",
        "ideal_humidity": "30–50%",
        "ideal_temperature": "15–25°C",
        "watering_interval_days": 5,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 365,
        "care_notes": "Регулярно удаляйте отцветшие соцветия. Зимой держите прохладнее.",
        "difficulty": "Лёгкая",
        "category": "Цветущие",
        "image_url": f"{WC}/Pelargonium_graveolens.jpg?width=400",
    },
    {
        "name": "Бегония вечноцветущая",
        "latin_name": "Begonia semperflorens",
        "description": "Компактное цветущее растение с маленькими яркими цветками и блестящими листьями.",
        "ideal_light": "Яркий рассеянный свет",
        "ideal_humidity": "50–60%",
        "ideal_temperature": "18–22°C",
        "watering_interval_days": 4,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 365,
        "care_notes": "Не допускайте перелива. Удаляйте увядшие цветки для продолжения цветения.",
        "difficulty": "Средняя",
        "category": "Цветущие",
        "image_url": f"{WC}/Begonia_x_semperflorens,_Gustave_rouge.jpg?width=400",
    },
    {
        "name": "Кротон",
        "latin_name": "Codiaeum variegatum",
        "description": "Яркое декоративное растение с пёстрыми кожистыми листьями красно-жёлто-зелёных оттенков.",
        "ideal_light": "Яркий свет, немного прямого солнца",
        "ideal_humidity": "60–80%",
        "ideal_temperature": "18–27°C",
        "watering_interval_days": 5,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 730,
        "care_notes": "Для яркого окраса нужен максимальный свет. Чувствителен к сквознякам.",
        "difficulty": "Сложная",
        "category": "Тропические",
        "image_url": f"{WC}/Colpfl05b.jpg?width=400",
    },
    {
        "name": "Юкка слоновая",
        "latin_name": "Yucca elephantipes",
        "description": "Эффектное деревце с жёсткими мечевидными листьями на стволе. Отличный акцент в интерьере.",
        "ideal_light": "Яркий свет, прямое солнце",
        "ideal_humidity": "30–50%",
        "ideal_temperature": "15–28°C",
        "watering_interval_days": 10,
        "fertilizing_interval_days": 30,
        "repotting_interval_days": 730,
        "care_notes": "Устойчива к засухе. Зимой сократите полив вдвое.",
        "difficulty": "Лёгкая",
        "category": "Деревья",
        "image_url": f"{WC}/Yucca_elephantipes.jpg?width=400",
    },
    {
        "name": "Пеперомия туполистная",
        "latin_name": "Peperomia obtusifolia",
        "description": "Компактный суккулент с плотными глянцевыми листьями. Отлично подходит для маленьких пространств.",
        "ideal_light": "Рассеянный или умеренный свет",
        "ideal_humidity": "40–60%",
        "ideal_temperature": "18–26°C",
        "watering_interval_days": 10,
        "fertilizing_interval_days": 30,
        "repotting_interval_days": 730,
        "care_notes": "Не переливайте — корни быстро гниют. Листья хранят воду.",
        "difficulty": "Лёгкая",
        "category": "Суккуленты",
        "image_url": f"{WC}/Peperomia_obtusifolia.jpg?width=400",
    },
    {
        "name": "Толстянка (денежное дерево)",
        "latin_name": "Crassula ovata",
        "description": "Суккулент с округлыми мясистыми листьями, похожий на миниатюрное дерево.",
        "ideal_light": "Яркий свет, прямое солнце",
        "ideal_humidity": "30–50%",
        "ideal_temperature": "15–26°C",
        "watering_interval_days": 14,
        "fertilizing_interval_days": 60,
        "repotting_interval_days": 730,
        "care_notes": "Поливайте редко, давайте полностью высохнуть почве. Живёт десятилетиями.",
        "difficulty": "Лёгкая",
        "category": "Суккуленты",
        "image_url": f"{WC}/Crassula_ovata_700.jpg?width=400",
    },
    {
        "name": "Хамедорея изящная",
        "latin_name": "Chamaedorea elegans",
        "description": "Компактная пальма с перистыми листьями. Одна из лучших комнатных пальм для тенистых мест.",
        "ideal_light": "Рассеянный свет, полутень",
        "ideal_humidity": "50–70%",
        "ideal_temperature": "18–27°C",
        "watering_interval_days": 7,
        "fertilizing_interval_days": 21,
        "repotting_interval_days": 730,
        "care_notes": "Опрыскивайте листья. Не выносит прямого солнца — листья сгорают.",
        "difficulty": "Средняя",
        "category": "Пальмы",
        "image_url": f"{WC}/ColliniaElegans.jpg?width=400",
    },
    {
        "name": "Стрелиция королевская",
        "latin_name": "Strelitzia reginae",
        "description": "Эффектное растение с оранжево-синими цветками, напоминающими экзотическую птицу.",
        "ideal_light": "Яркое прямое солнце",
        "ideal_humidity": "40–60%",
        "ideal_temperature": "18–28°C",
        "watering_interval_days": 7,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 1095,
        "care_notes": "Зимой сократите полив. Нужен большой горшок. Цветёт при хорошем освещении.",
        "difficulty": "Средняя",
        "category": "Цветущие",
        "image_url": f"{WC}/Strelitzia_reginae_DSC_0013.JPG?width=400",
    },
    {
        "name": "Нефролепис (бостонский папоротник)",
        "latin_name": "Nephrolepis exaltata",
        "description": "Пышный папоротник с дугообразными перистыми листьями. Отлично увлажняет воздух.",
        "ideal_light": "Рассеянный свет, без прямого солнца",
        "ideal_humidity": "60–80%",
        "ideal_temperature": "16–24°C",
        "watering_interval_days": 3,
        "fertilizing_interval_days": 21,
        "repotting_interval_days": 365,
        "care_notes": "Регулярно опрыскивайте. Не допускайте пересыхания почвы — листья быстро сохнут.",
        "difficulty": "Средняя",
        "category": "Папоротники",
        "image_url": f"{WC}/NephrolepisExaltata.jpg?width=400",
    },
    {
        "name": "Аглаонема",
        "latin_name": "Aglaonema commutatum",
        "description": "Декоративное теневыносливое растение с пёстрыми зелёно-серебристыми листьями.",
        "ideal_light": "Слабый или рассеянный свет",
        "ideal_humidity": "50–70%",
        "ideal_temperature": "18–27°C",
        "watering_interval_days": 7,
        "fertilizing_interval_days": 21,
        "repotting_interval_days": 730,
        "care_notes": "Идеальна для тёмных помещений. Не допускайте холодных сквозняков.",
        "difficulty": "Лёгкая",
        "category": "Тропические",
        "image_url": f"{WC}/Aglaonema_commutatum0.jpg?width=400",
    },
    {
        "name": "Шеффлера",
        "latin_name": "Schefflera arboricola",
        "description": "Деревце с крупными пальчатыми листьями. Быстро растёт и создаёт тропическую атмосферу.",
        "ideal_light": "Яркий рассеянный свет",
        "ideal_humidity": "50–70%",
        "ideal_temperature": "16–24°C",
        "watering_interval_days": 7,
        "fertilizing_interval_days": 21,
        "repotting_interval_days": 730,
        "care_notes": "Регулярно обрезайте для пышности. Летом можно выносить на балкон.",
        "difficulty": "Средняя",
        "category": "Деревья",
        "image_url": f"{WC}/Schefflera_arboricola1.jpg?width=400",
    },
    {
        "name": "Гиппеаструм (амариллис)",
        "latin_name": "Hippeastrum hybridum",
        "description": "Луковичное растение с крупными трубчатыми цветками красного, белого или розового цвета.",
        "ideal_light": "Яркий рассеянный свет",
        "ideal_humidity": "40–60%",
        "ideal_temperature": "18–23°C",
        "watering_interval_days": 7,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 730,
        "care_notes": "После цветения дайте луковице период покоя: убавьте полив, держите прохладнее.",
        "difficulty": "Средняя",
        "category": "Цветущие",
        "image_url": f"{WC}/Hippeastrum_reginae.jpg?width=400",
    },
    {
        "name": "Опунция",
        "latin_name": "Opuntia microdasys",
        "description": "Плоскосегментный кактус с пучками белых или жёлтых глохидий. Декоративен и неприхотлив.",
        "ideal_light": "Прямое солнце",
        "ideal_humidity": "20–40%",
        "ideal_temperature": "15–35°C",
        "watering_interval_days": 21,
        "fertilizing_interval_days": 60,
        "repotting_interval_days": 1095,
        "care_notes": "Глохидии очень острые — работайте в перчатках. Зимой почти не поливайте.",
        "difficulty": "Лёгкая",
        "category": "Кактусы",
        "image_url": f"{WC}/Opuntia_microdasys.jpg?width=400",
    },
    {
        "name": "Адиантум (венерин волос)",
        "latin_name": "Adiantum capillus-veneris",
        "description": "Изящный папоротник с тонкими черешками и маленькими веерообразными листочками.",
        "ideal_light": "Рассеянный свет без прямого солнца",
        "ideal_humidity": "70–90%",
        "ideal_temperature": "16–24°C",
        "watering_interval_days": 3,
        "fertilizing_interval_days": 30,
        "repotting_interval_days": 365,
        "care_notes": "Требует очень высокой влажности. Поставьте на поддон с водой и галькой.",
        "difficulty": "Сложная",
        "category": "Папоротники",
        "image_url": f"{WC}/ADIANTUM_CAPILLUS-VENERIS_-_MONTPOL_-_IB-082_(Falzia).jpg?width=400",
    },
    {
        "name": "Гузмания",
        "latin_name": "Guzmania lingulata",
        "description": "Бромелиевое растение с ярко-красным или оранжевым прицветником в центре розетки.",
        "ideal_light": "Рассеянный свет",
        "ideal_humidity": "60–80%",
        "ideal_temperature": "18–27°C",
        "watering_interval_days": 7,
        "fertilizing_interval_days": 30,
        "repotting_interval_days": 730,
        "care_notes": "Наливайте воду в воронку листьев. После отцветания дочерние розетки дают новые растения.",
        "difficulty": "Средняя",
        "category": "Цветущие",
        "image_url": f"{WC}/Bromeliaceae03.jpg?width=400",
    },
    {
        "name": "Маранта трёхцветная",
        "latin_name": "Maranta leuconeura",
        "description": "Тропическое растение с красивыми узорчатыми листьями. На ночь складывает листья — за это прозвана «молящейся травой».",
        "ideal_light": "Рассеянный свет без прямого солнца",
        "ideal_humidity": "60–80%",
        "ideal_temperature": "18–26°C",
        "watering_interval_days": 5,
        "fertilizing_interval_days": 21,
        "repotting_interval_days": 365,
        "care_notes": "Поливайте мягкой водой комнатной температуры. Опрыскивайте ежедневно. Не терпит сквозняков.",
        "difficulty": "Средняя",
        "category": "Тропические",
        "image_url": f"{WC}/Maranta_leuconeura3.jpg?width=400",
    },
    {
        "name": "Сенполия (узамбарская фиалка)",
        "latin_name": "Saintpaulia ionantha",
        "description": "Компактное цветущее растение с бархатистыми листьями и яркими цветками. Одно из самых популярных комнатных растений.",
        "ideal_light": "Яркий рассеянный свет, подходит фитолампа",
        "ideal_humidity": "50–60%",
        "ideal_temperature": "18–24°C",
        "watering_interval_days": 5,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 365,
        "care_notes": "Поливайте только в поддон — вода на листьях оставляет пятна. Избегайте холодных подоконников зимой.",
        "difficulty": "Средняя",
        "category": "Цветущие",
        "image_url": f"{WC}/Saintpaulia_ionantha.jpg?width=400",
    },
    {
        "name": "Хавортия полосатая",
        "latin_name": "Haworthia fasciata",
        "description": "Миниатюрный суккулент с тёмно-зелёными листьями, покрытыми белыми полосами. Идеально для маленьких пространств.",
        "ideal_light": "Рассеянный свет или полутень",
        "ideal_humidity": "30–50%",
        "ideal_temperature": "16–26°C",
        "watering_interval_days": 14,
        "fertilizing_interval_days": 60,
        "repotting_interval_days": 730,
        "care_notes": "Переносит тень лучше других суккулентов. Не заливайте — корни быстро гниют. Зимой поливайте раз в месяц.",
        "difficulty": "Лёгкая",
        "category": "Суккуленты",
        "image_url": f"{WC}/1_Haworthia_fasciata_-_small_plant_in_cultivation_-_CT.jpg?width=400",
    },
    {
        "name": "Сингониум стрелолистный",
        "latin_name": "Syngonium podophyllum",
        "description": "Быстрорастущая лиана с красивыми стреловидными листьями. Молодые листья однотонные, взрослые становятся крупными и лопастными.",
        "ideal_light": "Рассеянный или умеренный свет",
        "ideal_humidity": "50–70%",
        "ideal_temperature": "18–27°C",
        "watering_interval_days": 6,
        "fertilizing_interval_days": 21,
        "repotting_interval_days": 365,
        "care_notes": "Легко укореняется черенками. Опрыскивайте листья. Сок ядовит — работайте в перчатках.",
        "difficulty": "Лёгкая",
        "category": "Тропические",
        "image_url": f"{WC}/Syngonium_podophyllum.jpg?width=400",
    },
    {
        "name": "Фиттония",
        "latin_name": "Fittonia albivenis",
        "description": "Почвопокровное растение с эффектными листьями, расчерченными белыми, розовыми или красными прожилками.",
        "ideal_light": "Слабый или рассеянный свет",
        "ideal_humidity": "70–90%",
        "ideal_temperature": "18–26°C",
        "watering_interval_days": 3,
        "fertilizing_interval_days": 21,
        "repotting_interval_days": 365,
        "care_notes": "Требует очень высокой влажности. Идеальна для флорариумов. При пересыхании почвы резко вянет — поливайте регулярно.",
        "difficulty": "Сложная",
        "category": "Тропические",
        "image_url": f"{WC}/Fittonia_albivenis_WPC.jpg?width=400",
    },
    {
        "name": "Плющ обыкновенный",
        "latin_name": "Hedera helix",
        "description": "Популярное ампельное растение с резными листьями. Отлично очищает воздух и подходит для вертикального озеленения.",
        "ideal_light": "Любое, включая полутень",
        "ideal_humidity": "40–60%",
        "ideal_temperature": "12–22°C",
        "watering_interval_days": 7,
        "fertilizing_interval_days": 30,
        "repotting_interval_days": 730,
        "care_notes": "Любит прохладу — не держите рядом с батареями. Регулярно осматривайте на паутинного клеща.",
        "difficulty": "Лёгкая",
        "category": "Тропические",
        "image_url": f"{WC}/Hedera_helix_Dover.jpg?width=400",
    },
    {
        "name": "Лимонное дерево",
        "latin_name": "Citrus limon",
        "description": "Вечнозелёное плодовое деревце с ароматными белыми цветками и кислыми плодами. Украшение любого подоконника.",
        "ideal_light": "Яркое прямое солнце, южное окно",
        "ideal_humidity": "50–70%",
        "ideal_temperature": "18–27°C",
        "watering_interval_days": 5,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 730,
        "care_notes": "Летом выносите на балкон. Для плодоношения нужна зимняя прохлада (10–15°C). Опыляйте вручную кисточкой.",
        "difficulty": "Сложная",
        "category": "Деревья",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Lemon_tree02.jpg/500px-Lemon_tree02.jpg",
    },
    {
        "name": "Церопегия Вуда",
        "latin_name": "Ceropegia woodii",
        "description": "Изящная ампельная лиана с маленькими сердцевидными листьями на тонких нитевидных побегах.",
        "ideal_light": "Яркий рассеянный свет",
        "ideal_humidity": "30–50%",
        "ideal_temperature": "15–25°C",
        "watering_interval_days": 14,
        "fertilizing_interval_days": 60,
        "repotting_interval_days": 730,
        "care_notes": "Суккулент — переносит засуху, но не переполив. Образует клубеньки на побегах, которые можно использовать для размножения.",
        "difficulty": "Лёгкая",
        "category": "Суккуленты",
        "image_url": f"{WC}/Ceropegia_woodii.jpg?width=400",
    },
    {
        "name": "Мирт обыкновенный",
        "latin_name": "Myrtus communis",
        "description": "Вечнозелёный кустарник с мелкими глянцевыми листьями и белыми душистыми цветками. Символ долголетия.",
        "ideal_light": "Яркий свет, прямое солнце",
        "ideal_humidity": "50–60%",
        "ideal_temperature": "15–25°C",
        "watering_interval_days": 5,
        "fertilizing_interval_days": 21,
        "repotting_interval_days": 730,
        "care_notes": "Летом выносите на балкон. Зимой держите прохладнее (8–10°C). Хорошо поддаётся формовке и стрижке.",
        "difficulty": "Средняя",
        "category": "Деревья",
        "image_url": f"{WC}/Myrtus_communis_001.JPG?width=400",
    },
    {
        "name": "Каладиум",
        "latin_name": "Caladium bicolor",
        "description": "Тропическое клубневое растение с крупными полупрозрачными листьями невероятной красоты — белыми, розовыми, красными.",
        "ideal_light": "Яркий рассеянный свет",
        "ideal_humidity": "70–80%",
        "ideal_temperature": "20–30°C",
        "watering_interval_days": 4,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 365,
        "care_notes": "Зимой листья отмирают — это норма. Клубни храните сухими при 15–18°C. Весной снова сажайте. Сок ядовит.",
        "difficulty": "Сложная",
        "category": "Тропические",
        "image_url": f"{WC}/Caladium_bicolor.jpg?width=400",
    },
    {
        "name": "Гимнокалициум",
        "latin_name": "Gymnocalycium mihanovichii",
        "description": "Небольшой шаровидный кактус, часто продаётся в виде цветных привитых форм — красных, жёлтых, оранжевых.",
        "ideal_light": "Рассеянный свет (яркий для зелёных форм)",
        "ideal_humidity": "20–40%",
        "ideal_temperature": "15–28°C",
        "watering_interval_days": 14,
        "fertilizing_interval_days": 60,
        "repotting_interval_days": 730,
        "care_notes": "Цветные формы без хлорофилла нуждаются в прививке. Поливайте умеренно, зимой почти не поливайте.",
        "difficulty": "Лёгкая",
        "category": "Кактусы",
        "image_url": f"{WC}/Gymnocalycium_mihanovichii_4.JPG?width=400",
    },
    {
        "name": "Стрептокарпус",
        "latin_name": "Streptocarpus hybridus",
        "description": "Компактное цветущее растение с длинными морщинистыми листьями и многочисленными трубчатыми цветками всех оттенков.",
        "ideal_light": "Яркий рассеянный свет, подходит фитолампа",
        "ideal_humidity": "50–70%",
        "ideal_temperature": "18–24°C",
        "watering_interval_days": 5,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 365,
        "care_notes": "Поливайте в поддон, не мочите листья. Удаляйте отцветшие цветоносы для непрерывного цветения.",
        "difficulty": "Средняя",
        "category": "Цветущие",
        "image_url": f"{WC}/Streptocarpus.jpg?width=400",
    },
    {
        "name": "Цикас поникающий",
        "latin_name": "Cycas revoluta",
        "description": "Древнейшее растение, похожее на пальму. Растёт очень медленно, живёт сотни лет. Статусный элемент интерьера.",
        "ideal_light": "Яркий свет, немного прямого солнца",
        "ideal_humidity": "40–60%",
        "ideal_temperature": "15–30°C",
        "watering_interval_days": 14,
        "fertilizing_interval_days": 60,
        "repotting_interval_days": 1095,
        "care_notes": "Не трогайте и не переставляйте без необходимости. Листья разворачиваются раз в год. Все части ядовиты.",
        "difficulty": "Средняя",
        "category": "Пальмы",
        "image_url": f"{WC}/Cycas_inflorescence.jpg?width=400",
    },
    {
        "name": "Пилея китайская",
        "latin_name": "Pilea peperomioides",
        "description": "Модное растение с круглыми монетовидными листьями на длинных черешках. Легко размножается и охотно дарится друзьям.",
        "ideal_light": "Яркий рассеянный свет",
        "ideal_humidity": "40–60%",
        "ideal_temperature": "15–25°C",
        "watering_interval_days": 7,
        "fertilizing_interval_days": 30,
        "repotting_interval_days": 365,
        "care_notes": "Поворачивайте горшок каждую неделю для равномерного роста. Дочерние розетки легко отделяются и укореняются.",
        "difficulty": "Лёгкая",
        "category": "Тропические",
        "image_url": f"{WC}/Pilea_peperomioides.jpg?width=400",
    },
    {
        "name": "Алоказия амазонская",
        "latin_name": "Alocasia amazonica",
        "description": "Эффектное тропическое растение с тёмно-зелёными стреловидными листьями и контрастными белыми прожилками.",
        "ideal_light": "Яркий рассеянный свет без прямого солнца",
        "ideal_humidity": "70–90%",
        "ideal_temperature": "18–27°C",
        "watering_interval_days": 5,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 365,
        "care_notes": "Требует высокой влажности — ставьте рядом увлажнитель. Чувствительна к холоду и сквознякам. Сок ядовит.",
        "difficulty": "Сложная",
        "category": "Тропические",
        "image_url": f"{WC}/Alocasia_amazonica.jpg?width=400",
    },
    {
        "name": "Калатея орбифолия",
        "latin_name": "Calathea orbifolia",
        "description": "Роскошное растение с крупными округлыми листьями в серебристо-зелёную полоску. Складывает листья на ночь.",
        "ideal_light": "Слабый или рассеянный свет",
        "ideal_humidity": "60–80%",
        "ideal_temperature": "18–25°C",
        "watering_interval_days": 5,
        "fertilizing_interval_days": 21,
        "repotting_interval_days": 365,
        "care_notes": "Поливайте только мягкой отстоянной водой — чувствительна к фтору и хлору. Не переносит сквозняки и прямое солнце.",
        "difficulty": "Сложная",
        "category": "Тропические",
        "image_url": f"{WC}/Calathea_orbifolia.jpg?width=400",
    },
    {
        "name": "Пахира водная",
        "latin_name": "Pachira aquatica",
        "description": "Деревце с характерным плетёным стволом и крупными пальчатыми листьями. Символ удачи и достатка.",
        "ideal_light": "Яркий рассеянный свет",
        "ideal_humidity": "50–70%",
        "ideal_temperature": "18–27°C",
        "watering_interval_days": 10,
        "fertilizing_interval_days": 30,
        "repotting_interval_days": 730,
        "care_notes": "Переносит периодическую засуху. Плетёный ствол формируется пока деревце молодое. Не переставляйте без необходимости.",
        "difficulty": "Лёгкая",
        "category": "Деревья",
        "image_url": f"{WC}/Pachira_aquatica.jpg?width=400",
    },
    {
        "name": "Кливия",
        "latin_name": "Clivia miniata",
        "description": "Эффектное луковичное растение с ремневидными тёмно-зелёными листьями и яркими оранжевыми соцветиями.",
        "ideal_light": "Рассеянный свет, полутень",
        "ideal_humidity": "40–60%",
        "ideal_temperature": "15–25°C",
        "watering_interval_days": 10,
        "fertilizing_interval_days": 21,
        "repotting_interval_days": 1095,
        "care_notes": "Зимой держите при 10–12°C и почти не поливайте — это провоцирует цветение. Не переставляйте в период бутонизации. Ядовита.",
        "difficulty": "Средняя",
        "category": "Цветущие",
        "image_url": f"{WC}/Clivia_miniata.jpg?width=400",
    },
    {
        "name": "Глоксиния",
        "latin_name": "Sinningia speciosa",
        "description": "Клубневое растение с бархатистыми листьями и крупными колокольчатыми цветками ярких расцветок.",
        "ideal_light": "Яркий рассеянный свет, фитолампа",
        "ideal_humidity": "60–70%",
        "ideal_temperature": "18–24°C",
        "watering_interval_days": 4,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 365,
        "care_notes": "Поливайте в поддон — вода на листьях и цветках оставляет пятна. После отцветания дайте клубню период покоя (3 месяца в прохладе).",
        "difficulty": "Средняя",
        "category": "Цветущие",
        "image_url": f"{WC}/Gloxinia.jpg?width=400",
    },
    {
        "name": "Бугенвиллея",
        "latin_name": "Bougainvillea spectabilis",
        "description": "Яркое кустарниковое растение с бумажными прицветниками малинового, оранжевого или белого цвета.",
        "ideal_light": "Прямое солнце, южное окно",
        "ideal_humidity": "40–60%",
        "ideal_temperature": "18–30°C",
        "watering_interval_days": 7,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 730,
        "care_notes": "Для обильного цветения нужно много прямого солнца. Летом выносите на балкон. Зимой держите при 10–15°C с минимальным поливом.",
        "difficulty": "Средняя",
        "category": "Цветущие",
        "image_url": f"{WC}/Bougainvillea_spectabilis.jpg?width=400",
    },
    {
        "name": "Фуксия",
        "latin_name": "Fuchsia hybrida",
        "description": "Ампельное растение с изящными поникающими цветками в форме серёжек двух контрастных цветов.",
        "ideal_light": "Яркий рассеянный свет без прямого солнца",
        "ideal_humidity": "50–70%",
        "ideal_temperature": "15–22°C",
        "watering_interval_days": 3,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 365,
        "care_notes": "Любит прохладу — при температуре выше 25°C сбрасывает бутоны. Регулярно прищипывайте для пышности. Зимой держите при 5–10°C.",
        "difficulty": "Средняя",
        "category": "Цветущие",
        "image_url": f"{WC}/Fuchsia_hybrida.jpg?width=400",
    },
    {
        "name": "Кофейное дерево",
        "latin_name": "Coffea arabica",
        "description": "Компактное деревце с блестящими тёмно-зелёными листьями, белыми ароматными цветками и кофейными ягодами.",
        "ideal_light": "Яркий рассеянный свет",
        "ideal_humidity": "60–80%",
        "ideal_temperature": "18–26°C",
        "watering_interval_days": 5,
        "fertilizing_interval_days": 21,
        "repotting_interval_days": 730,
        "care_notes": "Поливайте мягкой водой. Летом можно выносить на балкон в полутень. Плоды вызревают около 9 месяцев — внутри настоящие кофейные зёрна.",
        "difficulty": "Средняя",
        "category": "Деревья",
        "image_url": f"{WC}/Coffea_arabica.jpg?width=400",
    },
    {
        "name": "Финиковая пальма карликовая",
        "latin_name": "Phoenix roebelenii",
        "description": "Изящная миниатюрная пальма с дугообразными перистыми листьями. Медленно растёт, долго живёт.",
        "ideal_light": "Яркий свет, немного прямого солнца",
        "ideal_humidity": "40–60%",
        "ideal_temperature": "16–27°C",
        "watering_interval_days": 7,
        "fertilizing_interval_days": 30,
        "repotting_interval_days": 730,
        "care_notes": "Опрыскивайте листья в жару. Основания листьев острые — работайте в перчатках. Зимой сократите полив.",
        "difficulty": "Средняя",
        "category": "Пальмы",
        "image_url": f"{WC}/Phoenix_roebelenii.jpg?width=400",
    },
    {
        "name": "Драцена Сандера",
        "latin_name": "Dracaena sanderiana",
        "description": "«Бамбук счастья» — на самом деле драцена, которую часто выращивают в воде с витыми стеблями. Популярный подарок.",
        "ideal_light": "Рассеянный свет, полутень",
        "ideal_humidity": "40–60%",
        "ideal_temperature": "15–25°C",
        "watering_interval_days": 7,
        "fertilizing_interval_days": 60,
        "repotting_interval_days": 730,
        "care_notes": "Можно выращивать в воде — меняйте раз в 2–4 недели. Не ставьте под прямые лучи — листья бледнеют. Чувствительна к фтору.",
        "difficulty": "Лёгкая",
        "category": "Тропические",
        "image_url": f"{WC}/Dracaena_sanderiana.jpg?width=400",
    },
    {
        "name": "Ктенанта",
        "latin_name": "Ctenanthe burle-marxii",
        "description": "Тропическое растение с удлинёнными листьями в серо-зелёную «ёлочку» и пурпурной нижней стороной.",
        "ideal_light": "Рассеянный или слабый свет",
        "ideal_humidity": "60–80%",
        "ideal_temperature": "18–26°C",
        "watering_interval_days": 5,
        "fertilizing_interval_days": 21,
        "repotting_interval_days": 365,
        "care_notes": "Родственница калатеи — такие же требования к мягкой воде и высокой влажности. Складывает листья ночью.",
        "difficulty": "Средняя",
        "category": "Тропические",
        "image_url": f"{WC}/Ctenanthe_burle-marxii.jpg?width=400",
    },
    {
        "name": "Рео пёстрое",
        "latin_name": "Tradescantia spathacea",
        "description": "Неприхотливое розеточное растение с мечевидными листьями: сверху тёмно-зелёными, снизу — ярко-пурпурными.",
        "ideal_light": "Яркий рассеянный или умеренный свет",
        "ideal_humidity": "40–60%",
        "ideal_temperature": "15–25°C",
        "watering_interval_days": 7,
        "fertilizing_interval_days": 30,
        "repotting_interval_days": 730,
        "care_notes": "Переносит полутень, но теряет насыщенность окраса. Лёгкое пересыхание допустимо. Сок раздражает кожу.",
        "difficulty": "Лёгкая",
        "category": "Тропические",
        "image_url": f"{WC}/Tradescantia_spathacea.jpg?width=400",
    },
    {
        "name": "Гортензия",
        "latin_name": "Hydrangea macrophylla",
        "description": "Пышный кустарник с огромными шарообразными соцветиями белого, синего, розового или сиреневого цвета.",
        "ideal_light": "Яркий рассеянный свет",
        "ideal_humidity": "60–80%",
        "ideal_temperature": "15–22°C",
        "watering_interval_days": 3,
        "fertilizing_interval_days": 14,
        "repotting_interval_days": 365,
        "care_notes": "Требует обильного полива — не допускайте пересыхания. Цвет соцветий зависит от pH почвы: кислая — синие, щелочная — розовые. Зимой держите при 5°C.",
        "difficulty": "Средняя",
        "category": "Цветущие",
        "image_url": f"{WC}/Hydrangea_macrophylla.jpg?width=400",
    },
    {
        "name": "Цереус перуанский",
        "latin_name": "Cereus repandus",
        "description": "Высокий столбчатый кактус с рёбрами и короткими колючками. Один из самых быстрорастущих кактусов.",
        "ideal_light": "Прямое солнце",
        "ideal_humidity": "20–40%",
        "ideal_temperature": "15–30°C",
        "watering_interval_days": 21,
        "fertilizing_interval_days": 60,
        "repotting_interval_days": 730,
        "care_notes": "Очень неприхотлив. Зимой не поливайте совсем и держите прохладнее (10°C). Крупные экземпляры цветут ночью.",
        "difficulty": "Лёгкая",
        "category": "Кактусы",
        "image_url": f"{WC}/Cereus_repandus.jpg?width=400",
    },
    {
        "name": "Аспарагус перистый",
        "latin_name": "Asparagus setaceus",
        "description": "Изящное растение с тонкими горизонтальными веточками, похожими на перья папоротника. Отлично смотрится в подвесных кашпо.",
        "ideal_light": "Яркий рассеянный или умеренный свет",
        "ideal_humidity": "50–70%",
        "ideal_temperature": "15–25°C",
        "watering_interval_days": 5,
        "fertilizing_interval_days": 21,
        "repotting_interval_days": 365,
        "care_notes": "Не допускайте пересыхания — иглы желтеют и осыпаются. Опрыскивайте. Летом можно выносить на балкон в полутень.",
        "difficulty": "Средняя",
        "category": "Тропические",
        "image_url": f"{WC}/Asparagus_setaceus.jpg?width=400",
    },
]

DIAGNOSTIC_TREE = [
    {"id": 1,  "question": "🌿 Каков общий вид вашего растения?",                      "is_root": True},
    {"id": 2,  "question": "🍃 Что именно происходит с листьями?",                     "is_root": False},
    {"id": 3,  "question": "🪵 Какие проблемы с корнями или стеблем?",                 "is_root": False},
    {"id": 4,  "question": "🟡 Листья желтеют — где именно?",                          "is_root": False},
    {"id": 5,  "question": "😔 Листья вянут — какая почва на ощупь?",                  "is_root": False},
    {"id": 6,  "question": "🟫 Что именно с коричневыми пятнами?",                     "is_root": False},
    {"id": 7,  "question": "🦠 Стебель мягкий — где именно?",                          "is_root": False},
    {"id": 8,  "question": "🐛 Что за вредители вы видите?",                           "is_root": False},
    {"id": 9,  "question": "📏 Когда именно заметен медленный рост?",                  "is_root": False},
    {"id": 10, "question": "🌡️ Какие изменения условий произошли недавно?",            "is_root": False},
    {"id": 11, "question": "🌀 Как именно скручиваются листья?",                       "is_root": False},
    {"id": 12, "question": "🫧 Что за пятна или налёт на поверхности листьев?",        "is_root": False},
    {"id": 13, "question": "😔 Листья вянут при нормальной почве — что ещё замечаете?","is_root": False},
]

DIAGNOSTIC_ANSWERS = [
    # Step 1 — общий вид
    {"step_id": 1, "answer_text": "🍂 Проблемы с листьями",                "next_step_id": 2,    "diagnosis": None, "recommendation": None},
    {"step_id": 1, "answer_text": "🪵 Проблемы со стеблем или корнями",    "next_step_id": 3,    "diagnosis": None, "recommendation": None},
    {"step_id": 1, "answer_text": "🌸 Растение не цветёт",                 "next_step_id": None,
     "diagnosis": "Недостаток света или питательных веществ",
     "recommendation": "Переставьте в более светлое место. Подкармливайте удобрением для цветущих растений каждые 2 недели. Убедитесь, что растение достигло возраста цветения."},
    {"step_id": 1, "answer_text": "🐛 Вижу вредителей на растении",        "next_step_id": 8,    "diagnosis": None, "recommendation": None},
    {"step_id": 1, "answer_text": "📏 Растение очень медленно растёт",      "next_step_id": 9,    "diagnosis": None, "recommendation": None},
    {"step_id": 1, "answer_text": "🌡️ Проблемы после изменения условий",   "next_step_id": 10,   "diagnosis": None, "recommendation": None},

    # Step 2 — листья
    {"step_id": 2, "answer_text": "🟡 Листья желтеют",                     "next_step_id": 4,    "diagnosis": None, "recommendation": None},
    {"step_id": 2, "answer_text": "😔 Листья вянут и повисают",             "next_step_id": 5,    "diagnosis": None, "recommendation": None},
    {"step_id": 2, "answer_text": "🟫 Коричневые пятна или края",           "next_step_id": 6,    "diagnosis": None, "recommendation": None},
    {"step_id": 2, "answer_text": "🍂 Листья активно опадают",              "next_step_id": None,
     "diagnosis": "Стресс от смены условий или сквозняк",
     "recommendation": "Проверьте наличие сквозняков. Не переставляйте горшок. Обеспечьте стабильную температуру 18–24°C. Опрыскайте листья тёплой водой."},
    {"step_id": 2, "answer_text": "🌀 Листья скручиваются",                 "next_step_id": 11,   "diagnosis": None, "recommendation": None},
    {"step_id": 2, "answer_text": "🫧 Пятна или налёт на поверхности",      "next_step_id": 12,   "diagnosis": None, "recommendation": None},

    # Step 3 — стебель/корни
    {"step_id": 3, "answer_text": "🦠 Стебель мягкий или загнивающий",     "next_step_id": 7,    "diagnosis": None, "recommendation": None},
    {"step_id": 3, "answer_text": "🌱 Корни выпирают из горшка",            "next_step_id": None,
     "diagnosis": "Растению тесно — пора пересаживать",
     "recommendation": "Пересадите весной в горшок на 2–3 см больше. Аккуратно расправьте корни. Используйте свежий грунт, подходящий для данного вида."},
    {"step_id": 3, "answer_text": "📏 Стебель истончился и вытянулся",      "next_step_id": None,
     "diagnosis": "Недостаток света (этиоляция)",
     "recommendation": "Переставьте ближе к окну или установите фитолампу на 10–12 часов в сутки. Обрежьте вытянувшиеся побеги для стимуляции густоты."},
    {"step_id": 3, "answer_text": "🔴 Стебель у основания потемнел",        "next_step_id": None,
     "diagnosis": "Начало корневой гнили или грибковой инфекции",
     "recommendation": "Немедленно проверьте корни. Удалите поражённые части, обработайте срезы фунгицидом. Пересадите в свежий сухой грунт с хорошим дренажем."},
    {"step_id": 3, "answer_text": "💪 Стебель крепкий, но сок вытекает",   "next_step_id": None,
     "diagnosis": "Механическое повреждение или слишком обильный полив",
     "recommendation": "Обработайте место повреждения толчёным активированным углём. Сократите полив. Обеспечьте хорошую вентиляцию."},

    # Step 4 — пожелтение
    {"step_id": 4, "answer_text": "👴 Нижние старые листья",               "next_step_id": None,
     "diagnosis": "Естественное старение листьев — это норма",
     "recommendation": "Просто удалите пожелтевшие листья. Если процесс ускоряется — проверьте питание и полив."},
    {"step_id": 4, "answer_text": "🌱 Молодые и верхние листья",           "next_step_id": None,
     "diagnosis": "Хлороз — нехватка железа или азота",
     "recommendation": "Подкормите хелатом железа или комплексным удобрением с микроэлементами. Оптимальный pH почвы — 5.5–6.5. При высоком pH железо не усваивается."},
    {"step_id": 4, "answer_text": "🌿 Равномерно жёлтеет всё растение",    "next_step_id": None,
     "diagnosis": "Переполив или корневая гниль",
     "recommendation": "Дайте почве полностью просохнуть. Проверьте дренажные отверстия. Если корни почернели — обрежьте, обработайте фунгицидом, пересадите."},
    {"step_id": 4, "answer_text": "📍 Желтеют листья с одной стороны",     "next_step_id": None,
     "diagnosis": "Неравномерное освещение или ожог",
     "recommendation": "Разворачивайте горшок на 90° каждые 1–2 недели. Уберите от прямых лучей, если жёлтая сторона обращена к солнцу."},

    # Step 5 — увядание
    {"step_id": 5, "answer_text": "🏜️ Почва сухая, горшок лёгкий",        "next_step_id": None,
     "diagnosis": "Острая нехватка влаги",
     "recommendation": "Погрузите горшок в воду на 15–20 минут для равномерного увлажнения. Опрыскайте листья. Впредь не допускайте полного пересыхания."},
    {"step_id": 5, "answer_text": "💧 Почва влажная или мокрая",           "next_step_id": None,
     "diagnosis": "Переполив или корневая гниль",
     "recommendation": "Прекратите полив. Проверьте дренаж. Если корни почернели и неприятно пахнут — пересадите, удалив гнилые части. Обработайте срезы углём."},
    {"step_id": 5, "answer_text": "🌿 Почва нормальная — не сухая, не мокрая", "next_step_id": 13, "diagnosis": None, "recommendation": None},
    {"step_id": 5, "answer_text": "🪨 Вода не впитывается, стекает по краям","next_step_id": None,
     "diagnosis": "Почва слишком уплотнилась или гидрофобная",
     "recommendation": "Погрузите горшок целиком в воду на 30 минут до полного намокания. После — взрыхлите верхний слой почвы. При сильном уплотнении пересадите в свежий рыхлый грунт."},

    # Step 6 — коричневые пятна
    {"step_id": 6, "answer_text": "📐 Только кончики и края коричневые",   "next_step_id": None,
     "diagnosis": "Низкая влажность воздуха или жёсткая вода",
     "recommendation": "Используйте увлажнитель воздуха или поддон с галькой и водой. Поливайте отстоянной или фильтрованной водой. Опрыскивайте листья."},
    {"step_id": 6, "answer_text": "☀️ Сухие белёсые пятна на солнечной стороне", "next_step_id": None,
     "diagnosis": "Солнечный ожог",
     "recommendation": "Притените окно или уберите от прямых лучей. Адаптируйте к яркому свету постепенно. Обожжённые листья не восстановятся — можно обрезать."},
    {"step_id": 6, "answer_text": "💧 Мокрые тёмные пятна с ободком",      "next_step_id": None,
     "diagnosis": "Грибковая пятнистость",
     "recommendation": "Удалите поражённые листья. Обработайте фунгицидом (Фитоспорин, хлорокись меди). Не опрыскивайте листья вечером, улучшите вентиляцию."},
    {"step_id": 6, "answer_text": "🟤 Ржавые или рыжеватые пятна",         "next_step_id": None,
     "diagnosis": "Ржавчина или повреждение трипсами",
     "recommendation": "Осмотрите нижнюю сторону листьев. При насекомых — инсектицид, при грибке — фунгицид на основе меди. Удалите поражённые листья."},

    # Step 7 — мягкий стебель
    {"step_id": 7, "answer_text": "⬇️ У самого основания стебля",          "next_step_id": None,
     "diagnosis": "Корневая гниль от переполива",
     "recommendation": "Срочно пересадите: удалите гнилые корни до здоровой ткани, обработайте срезы фунгицидом. Посадите в свежий рыхлый грунт. Сократите полив вдвое."},
    {"step_id": 7, "answer_text": "🔀 В середине стебля или на черенках",  "next_step_id": None,
     "diagnosis": "Бактериальная инфекция или механическое повреждение",
     "recommendation": "Обрежьте до здоровой (белой/зелёной) ткани. Обработайте срез активированным углём или фунгицидом. Обеспечьте хорошую вентиляцию."},
    {"step_id": 7, "answer_text": "🍃 Мягкие и поникшие черешки листьев",  "next_step_id": None,
     "diagnosis": "Переполив или дефицит кальция",
     "recommendation": "Дайте почве просохнуть. Подкормите удобрением с кальцием. Проверьте корни — при гнили удалите поражённые части и пересадите."},
    {"step_id": 7, "answer_text": "🌿 Всё растение мягкое и вялое целиком", "next_step_id": None,
     "diagnosis": "Тяжёлый переполив или критическая нехватка воды",
     "recommendation": "Достаньте растение из горшка и осмотрите корни. Чёрные мокрые корни — гниль, нужна срочная пересадка. Сухие белые корни — полейте методом погружения."},

    # Step 8 — вредители
    {"step_id": 8, "answer_text": "🕷️ Паутинка и мелкие ползающие точки", "next_step_id": None,
     "diagnosis": "Паутинный клещ",
     "recommendation": "Промойте листья мыльным раствором (1 ч.л. мыла на 1 л воды). Обработайте акарицидом (Фитоверм, Актеллик). Повысьте влажность воздуха. Повторите через 7–10 дней."},
    {"step_id": 8, "answer_text": "🪲 Белый пушок или мучнистые комочки",  "next_step_id": None,
     "diagnosis": "Мучнистый червец",
     "recommendation": "Уберите насекомых ватным тампоном со спиртом. Обработайте Актарой или Конфидором. Изолируйте от других растений. Повторяйте каждые 10 дней."},
    {"step_id": 8, "answer_text": "🟤 Коричневые бляшки на стеблях",       "next_step_id": None,
     "diagnosis": "Щитовка",
     "recommendation": "Сотрите бляшки тампоном со спиртом. Обработайте системным инсектицидом (Актара). Повторяйте каждые 10 дней минимум 3 раза."},
    {"step_id": 8, "answer_text": "🐜 Мошки летают из почвы",              "next_step_id": None,
     "diagnosis": "Грибные комарики (сциариды)",
     "recommendation": "Дайте почве просохнуть между поливами — личинки живут во влажном грунте. Обработайте почву Базудином. Используйте жёлтые клеевые ловушки."},
    {"step_id": 8, "answer_text": "🟢 Зелёные или чёрные скопления на побегах", "next_step_id": None,
     "diagnosis": "Тля",
     "recommendation": "Промойте под тёплым душем. Обработайте мыльным раствором или инсектицидом (Фитоверм, Интавир). Особое внимание — молодым побегам. Повторите через неделю."},

    # Step 9 — медленный рост
    {"step_id": 9, "answer_text": "☀️ Весной и летом (в сезон роста)",     "next_step_id": None,
     "diagnosis": "Нехватка питания или тесный горшок",
     "recommendation": "Подкормите комплексным удобрением с азотом (NPK). Проверьте, не выпирают ли корни — возможно пересадить. Убедитесь в достаточном освещении (6+ часов)."},
    {"step_id": 9, "answer_text": "❄️ Только зимой",                       "next_step_id": None,
     "diagnosis": "Нормальный период покоя",
     "recommendation": "Это норма для большинства растений. Сократите полив и удобрение зимой. Весной рост возобновится. Не пересаживайте зимой без необходимости."},
    {"step_id": 9, "answer_text": "🔄 Круглый год, совсем не растёт",      "next_step_id": None,
     "diagnosis": "Хроническая нехватка света или переполненные корни",
     "recommendation": "Переставьте в более светлое место или добавьте фитолампу. При сильном переплетении корней — пересадите весной. Подкармливайте регулярно."},
    {"step_id": 9, "answer_text": "🪴 После недавней пересадки",            "next_step_id": None,
     "diagnosis": "Адаптационный период после пересадки — это нормально",
     "recommendation": "Дайте 3–6 недель на укоренение. Не вносите удобрения первые 2 месяца после пересадки. Обеспечьте рассеянный свет и умеренный полив."},

    # Step 10 — изменение условий
    {"step_id": 10, "answer_text": "🚶 Переставили горшок на новое место",  "next_step_id": None,
     "diagnosis": "Адаптационный стресс от смены места",
     "recommendation": "Дайте 2–4 недели на адаптацию. Не переставляйте снова. Небольшой листопад в этот период — норма. Обеспечьте стабильные условия."},
    {"step_id": 10, "answer_text": "❄️ Похолодало или появился сквозняк",  "next_step_id": None,
     "diagnosis": "Холодовой стресс",
     "recommendation": "Уберите от окон и кондиционеров. Большинство комнатных растений плохо переносят температуру ниже 15°C. Используйте тепловой экран у окна зимой."},
    {"step_id": 10, "answer_text": "🔥 Стало жарче, рядом батарея",        "next_step_id": None,
     "diagnosis": "Тепловой стресс и пересыхание воздуха",
     "recommendation": "Уберите от батарей и обогревателей. Поставьте поддон с галькой и водой. Увлажняйте воздух, участите полив в жаркий период."},
    {"step_id": 10, "answer_text": "🏠 Растение недавно купили или привезли","next_step_id": None,
     "diagnosis": "Адаптационный стресс после смены среды",
     "recommendation": "Карантин 2–3 недели отдельно от других растений. Не пересаживайте сразу. Рассеянный свет, умеренный полив. Обработайте профилактически от вредителей."},

    # Step 11 — скручивание листьев
    {"step_id": 11, "answer_text": "⬆️ Листья закручиваются вверх и внутрь","next_step_id": None,
     "diagnosis": "Перегрев или острая нехватка влаги",
     "recommendation": "Проверьте температуру — держите до 27°C. Срочно полейте и опрыскайте. Уберите от прямого солнца в жаркие часы."},
    {"step_id": 11, "answer_text": "⬇️ Листья опускаются и скручиваются вниз","next_step_id": None,
     "diagnosis": "Переполив или холодный воздух",
     "recommendation": "Дайте почве просохнуть. Уберите от сквозняков и холодных окон. Проверьте корни на гниль."},
    {"step_id": 11, "answer_text": "🔄 Края листьев сворачиваются по всей длине","next_step_id": None,
     "diagnosis": "Засуха или трипсы/клещ",
     "recommendation": "Полейте и осмотрите нижнюю сторону листьев. При мелких насекомых — обработайте инсектицидом. Повысьте влажность воздуха."},
    {"step_id": 11, "answer_text": "🌱 Скручиваются только новые молодые листья","next_step_id": None,
     "diagnosis": "Нехватка кальция или бора, либо слишком низкая влажность",
     "recommendation": "Молодые листья особенно чувствительны к питанию. Подкормите удобрением с микроэлементами. Повысьте влажность воздуха до 50–60% и полейте мягкой водой."},

    # Step 12 — налёт и пятна
    {"step_id": 12, "answer_text": "⬜ Белый мучнистый налёт на листьях",  "next_step_id": None,
     "diagnosis": "Мучнистая роса (грибковое заболевание)",
     "recommendation": "Удалите поражённые листья. Обработайте раствором соды (1 ч.л. на 1 л воды) или фунгицидом. Улучшите вентиляцию, не опрыскивайте вечером."},
    {"step_id": 12, "answer_text": "💛 Мелкие жёлтые или серебристые точки","next_step_id": None,
     "diagnosis": "Трипсы или паутинный клещ",
     "recommendation": "Осмотрите нижнюю сторону листьев. Обработайте акарицидом (клещ) или инсектицидом (трипсы). Повторите через 7 дней, 3–4 раза."},
    {"step_id": 12, "answer_text": "💦 Листья липкие и блестят",           "next_step_id": None,
     "diagnosis": "Медвяная роса от тли, щитовки или белокрылки",
     "recommendation": "Промойте листья тёплой водой. Найдите и уничтожьте вредителей инсектицидом. Липкость — это их выделения, на них может развиться сажистый грибок."},
    {"step_id": 12, "answer_text": "💧 Прозрачные водянистые пузырьки",    "next_step_id": None,
     "diagnosis": "Отёк тканей (эдема) от переполива",
     "recommendation": "Сократите полив и улучшите дренаж. Пятна не исчезнут, но новые не появятся. Обеспечьте хорошее освещение и вентиляцию."},

    # Step 13 — увядание при нормальной почве
    {"step_id": 13, "answer_text": "🪨 Горшок очень тяжёлый, корни переплелись","next_step_id": None,
     "diagnosis": "Корневая система забита — растению тесно",
     "recommendation": "Пересадите весной в горшок на 2–3 см больше. Аккуратно расправьте корни, используйте свежий питательный грунт."},
    {"step_id": 13, "answer_text": "🌡️ В комнате очень холодно (ниже 15°C)","next_step_id": None,
     "diagnosis": "Холодовой шок — корни не впитывают воду",
     "recommendation": "Перенесите в тёплое место (18–22°C). Не поливайте холодной водой. Тургор восстановится после согревания."},
    {"step_id": 13, "answer_text": "💨 Рядом кондиционер или открытое окно","next_step_id": None,
     "diagnosis": "Пересыхание листьев из-за потока воздуха",
     "recommendation": "Уберите от источника потока. Опрыскайте листья. Повысьте влажность вокруг растения."},
    {"step_id": 13, "answer_text": "🧪 Недавно вносили удобрение",          "next_step_id": None,
     "diagnosis": "Ожог корней от избытка удобрений",
     "recommendation": "Обильно пролейте почву чистой водой, чтобы вымыть лишние соли (3–4 объёма горшка). Не удобряйте ближайший месяц. Используйте вдвое меньшую концентрацию, чем указано."},
]


def seed():
    db = SessionLocal()
    try:
        if db.query(models.CatalogPlant).count() == 0:
            for p in CATALOG_PLANTS:
                db.add(models.CatalogPlant(**p))
            db.commit()
            print(f"Добавлено {len(CATALOG_PLANTS)} растений в каталог")
        else:
            updated = 0
            added = 0
            for p in CATALOG_PLANTS:
                plant = db.query(models.CatalogPlant).filter(
                    models.CatalogPlant.name == p["name"]
                ).first()
                if plant is None:
                    db.add(models.CatalogPlant(**p))
                    added += 1
                elif p.get("image_url") and not plant.image_url.startswith("/uploads/catalog/"):
                    plant.image_url = p["image_url"]
                    updated += 1
            if added or updated:
                db.commit()
                if added:
                    print(f"Добавлено новых растений: {added}")
                if updated:
                    print(f"Обновлено изображений: {updated}")

        # Скачиваем изображения локально для всех растений без локального файла
        plants = db.query(models.CatalogPlant).all()
        downloaded = 0
        for plant in plants:
            if plant.image_url and not plant.image_url.startswith("/uploads/catalog/"):
                local_path = _download_image(plant.id, plant.image_url)
                if local_path:
                    plant.image_url = local_path
                    downloaded += 1
        if downloaded:
            db.commit()
            print(f"Скачано изображений локально: {downloaded}")

        # Всегда пересоздаём дерево диагностики (статичные данные)
        db.query(models.DiagnosticAnswer).delete()
        db.query(models.DiagnosticStep).delete()
        db.commit()
        for step_data in DIAGNOSTIC_TREE:
            db.add(models.DiagnosticStep(
                id=step_data["id"],
                question=step_data["question"],
                is_root=step_data["is_root"],
            ))
        db.commit()
        for ans_data in DIAGNOSTIC_ANSWERS:
            db.add(models.DiagnosticAnswer(**ans_data))
        db.commit()
        print(f"Диагностика: {len(DIAGNOSTIC_TREE)} шагов, {len(DIAGNOSTIC_ANSWERS)} ответов")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
